---
- name: Asegúrarse de que el módulo MySQL Python esté instalado
  hosts: ubuntu
  become: true

  tasks:

  - name: Instalar dependencias para  Python 2.7
    ansible.builtin.apt:
      name: python-pip
      state: present
    when: ansible_python_version is version('3.0', '<')

  - name: Instalar  MySQL-python para Python 2.7
    ansible.builtin.pip:
      name: 
        - PyMySQL
        - MySQL-python
    when: ansible_python_version is version('3.0', '<')

  - name: Instalar dependencias para Python 3.X
    ansible.builtin.apt:
      name: python3-pip
      state: present
    when: ansible_python_version is version('3.0', '>=')

      #  - name: Instalar mysqlclient y PyMySQL para Python 3.X
      #    ansible.builtin.pip:
      #      name: 
        #- mysqlclienti
        # - PyMySQL
        #      executable: pipx
        #    when: ansible_python_version is version('3.0', '>=')

