---
- name: Configurar acceso a MariaDB con archivo .my.cnf
  hosts: ubuntu
  become: true
  tasks:
    - name: Crear archivo de configuración /root/.my.cnf
      ansible.builtin.blockinfile:
        path: /root/.my.cnf
        create: true
        block: |
          [client]
          user= root
          password= "dbadmin"

    - name: Asegurar permisos en /root/.my.cnf
      ansible.builtin.file:
        path: /root/.my.cnf
        owner: root
        group: root
        mode: '0600'

  handlers:
    - name: Reiniciar MariaDB
      systemd:
        name: mariadb
        state: restarted

